language: scala

scala:
  - 2.11.11
  - 2.12.3

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test it:compile
  - sbt "project sharedJS" "fastOptJS"
  - sbt "project http4s-clientJS" "fastOptJS"
